env:
  browser: true
  es6: true
extends:
  - google
parserOptions:
  ecmaVersion: 2015
  sourceType: module

rules:
  linebreak-style:
    - error
    - windows

overrides:
  - files: '*.d.ts'
    parser: typescript-eslint-parser
    rules:
      no-unused-vars: off
      require-jsdoc: off
      camelcase: off
